models:
  - type: main
    engine: azure
    model: gpt-4-1106-preview
    parameters:
      azure_endpoint: https://imageanalysis.openai.azure.com/
      api_version: 2023-07-01-preview
      deployment_name: gpt-4-1106-preview
      api_key: 83660e6c390a4a169bfe98614f8e6873

rails:
  input:
    flows:
      - self check input
